### ISSUE TITLE
What's the difference between StackMIA and StackMIAsub?

### ISSUE THREAD

**Issue by JaydencoolCC** [yyy01/PAC#1]
As far as I know,  StackMIA is based on the Stack Exchange dataset, which is collected after  May 1, 2023. Does this imply that the samples in StackMIA are non-members? So I want to know how is StackMIAsub constructed.  Whether the non-members of StackMIAsub are StackMIA? Can you describe in detail(timestamp, source) how members and non-members are divided in StackMIAsub?

**Comment by JaydencoolCC** [comment]
<img width="815" alt="截屏2024-07-28 16 15 58" src="https://github.com/user-attachments/assets/ea787d32-1feb-4d7a-9112-aafcef04bf09">
Does the information of the division of members and non-members in the paper represent StackMIAsub?

**Comment by JaydencoolCC** [comment]
@yyy01  Thank you for your good work！

**Comment by yyy01** [comment]
> <img alt="截屏2024-07-28 16 15 58" width="815" src="https://private-user-images.githubusercontent.com/59495205/352798592-ea787d32-1feb-4d7a-9112-aafcef04bf09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDM3MDgsIm5iZiI6MTcyNDIwMzQwOCwicGF0aCI6Ii81OTQ5NTIwNS8zNTI3OTg1OTItZWE3ODdkMzItMWZlYi00ZDdhLTkxMTItYWFmY2VmMDRiZjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAxMjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMDNjMmUwNjg0ZTEzODVjZGRlNTM0NjA0YzYyM2E5NTMyYjE3ZGRhOGUxZGY5MTQwNDdiYTRiMWJjZjhlZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aN--ojrlm1amVbDF1FiLcN-x5b9L4ENhCUyjjtMcUgs"> Does the information of the division of members and non-members in the paper represent StackMIAsub?

Yes, your understanding is correct. stackmia considers data from every month after 2023 as a dataset or framework. And stackmiasub specifically selected May 1, 2023 as a cutoff to divide non-members (as a benhmark).

Sorry for the late reply!

**Comment by JaydencoolCC** [comment]
Thanks!
