### ISSUE TITLE
How to reproduce the results of Table 4 in this paper?

### ISSUE THREAD

**Issue by Li-XYi** [yyy01/PAC#2]
I'd like to reproduce the results of Table 4 in this paper, but can't find any detail instructions. I'll appreciate that if anyone could tell me how to do.

**Comment by yyy01** [comment]
> I'd like to reproduce the results of Table 4 in this paper, but can't find any detail instructions. I'll appreciate that if anyone could tell me how to do.

For the dataset introduced in Table 4, we use the original dataset. Run the code with the original dataset to get the results. For GPT-3.5 or GPT-4 models, please note that the probability tracking algorithm will introduce additional costs.

Sorry for the untimely reply!
